apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx-deployment
    labels:
        name: nginx-deployment
spec:
    replicas: 3
    selector:
        matchLabels:
            server: nginx
    strategy:
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 1
        type: RollingUpdate
    template:
        metadata:
            labels:
                name: nginxproxy
                server: nginx
        spec:
            containers:
                - image: nginx:lastest
                  name: nginxcontainer
                  resources:
                      limits:
                          cpu: "20m"
                          memory: "55M"
                  ports:
                      - containerPort: 5000
                        name: my-name
            restartPolicy: Always
            imagePullPolicy: Always
