apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: myreplicaset
spec:
    replicas: 3
    selector:
        matchLabels:
            app: nginxproxy
    template:
        metadata:
            name: proxyapp
            labels:
                app: nginxproxy
        spec:
            containers:
                - name: nginxcontainer
                  image: nginx:latest
                  resources:
                      limits:
                          memory: "128Mi"
                          cpu: "500m"
                  ports:
                      - containerPort: 80
